// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: Proto/models.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace SEFApp.Proto {

  /// <summary>Holder for reflection information generated from Proto/models.proto</summary>
  public static partial class ModelsReflection {

    #region Descriptor
    /// <summary>File descriptor for Proto/models.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static ModelsReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChJQcm90by9tb2RlbHMucHJvdG8SA2F0ayJ4CgpDb3Vwb25JdGVtEgwKBG5h",
            "bWUYASABKAkSDQoFcHJpY2UYAiABKAMSDAoEdW5pdBgDIAEoCRIQCghxdWFu",
            "dGl0eRgEIAEoAhINCgV0b3RhbBgFIAEoAxIQCgh0YXhfcmF0ZRgGIAEoCRIM",
            "CgR0eXBlGAcgASgJIjkKB1BheW1lbnQSHgoEdHlwZRgBIAEoDjIQLmF0ay5Q",
            "YXltZW50VHlwZRIOCgZhbW91bnQYAiABKAMiRgoIVGF4R3JvdXASEAoIdGF4",
            "X3JhdGUYASABKAkSFQoNdG90YWxfZm9yX3RheBgCIAEoAxIRCgl0b3RhbF90",
            "YXgYAyABKAMipAMKCVBvc0NvdXBvbhITCgtidXNpbmVzc19pZBgBIAEoBBIR",
            "Cgljb3Vwb25faWQYAiABKAQSEQoJYnJhbmNoX2lkGAMgASgEEhAKCGxvY2F0",
            "aW9uGAQgASgJEhMKC29wZXJhdG9yX2lkGAUgASgJEg4KBnBvc19pZBgGIAEo",
            "BBIWCg5hcHBsaWNhdGlvbl9pZBgHIAEoBBIXCg92ZXJpZmljYXRpb25fbm8Y",
            "CCABKAkSHQoEdHlwZRgJIAEoDjIPLmF0ay5Db3Vwb25UeXBlEgwKBHRpbWUY",
            "CiABKAMSHgoFaXRlbXMYCyADKAsyDy5hdGsuQ291cG9uSXRlbRIeCghwYXlt",
            "ZW50cxgMIAMoCzIMLmF0ay5QYXltZW50Eg0KBXRvdGFsGA0gASgDEiEKCnRh",
            "eF9ncm91cHMYDiADKAsyDS5hdGsuVGF4R3JvdXASEQoJdG90YWxfdGF4GA8g",
            "ASgDEhQKDHRvdGFsX25vX3RheBgQIAEoAxIUCgxyZWZlcmVuY2Vfbm8YESAB",
            "KAQSFgoOdG90YWxfZGlzY291bnQYEiABKAMi+gEKDUNpdGl6ZW5Db3Vwb24S",
            "EwoLYnVzaW5lc3NfaWQYASABKAQSDgoGcG9zX2lkGAIgASgEEhEKCWNvdXBv",
            "bl9pZBgDIAEoBBIRCglicmFuY2hfaWQYBCABKAQSHQoEdHlwZRgFIAEoDjIP",
            "LmF0ay5Db3Vwb25UeXBlEgwKBHRpbWUYBiABKAMSDQoFdG90YWwYByABKAMS",
            "IQoKdGF4X2dyb3VwcxgIIAMoCzINLmF0ay5UYXhHcm91cBIRCgl0b3RhbF90",
            "YXgYCSABKAMSFAoMdG90YWxfbm9fdGF4GAogASgDEhYKDnRvdGFsX2Rpc2Nv",
            "dW50GAsgASgDKjMKCkNvdXBvblR5cGUSGwoXQ09VUE9OX1RZUEVfVU5TUEVD",
            "SUZJRUQQABIICgRTYWxlEAEqUgoLUGF5bWVudFR5cGUSHAoYUEFZTUVOVF9U",
            "WVBFX1VOU1BFQ0lGSUVEEAASCAoEQ2FzaBABEg4KCkNyZWRpdENhcmQQAhIL",
            "CgdWb3VjaGVyEANCD6oCDFNFRkFwcC5Qcm90b2IGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::SEFApp.Proto.CouponType), typeof(global::SEFApp.Proto.PaymentType), }, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::SEFApp.Proto.CouponItem), global::SEFApp.Proto.CouponItem.Parser, new[]{ "Name", "Price", "Unit", "Quantity", "Total", "TaxRate", "Type" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::SEFApp.Proto.Payment), global::SEFApp.Proto.Payment.Parser, new[]{ "Type", "Amount" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::SEFApp.Proto.TaxGroup), global::SEFApp.Proto.TaxGroup.Parser, new[]{ "TaxRate", "TotalForTax", "TotalTax" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::SEFApp.Proto.PosCoupon), global::SEFApp.Proto.PosCoupon.Parser, new[]{ "BusinessId", "CouponId", "BranchId", "Location", "OperatorId", "PosId", "ApplicationId", "VerificationNo", "Type", "Time", "Items", "Payments", "Total", "TaxGroups", "TotalTax", "TotalNoTax", "ReferenceNo", "TotalDiscount" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::SEFApp.Proto.CitizenCoupon), global::SEFApp.Proto.CitizenCoupon.Parser, new[]{ "BusinessId", "PosId", "CouponId", "BranchId", "Type", "Time", "Total", "TaxGroups", "TotalTax", "TotalNoTax", "TotalDiscount" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Enums
  /// <summary>
  /// Enums
  /// </summary>
  public enum CouponType {
    [pbr::OriginalName("COUPON_TYPE_UNSPECIFIED")] Unspecified = 0,
    [pbr::OriginalName("Sale")] Sale = 1,
  }

  public enum PaymentType {
    [pbr::OriginalName("PAYMENT_TYPE_UNSPECIFIED")] Unspecified = 0,
    [pbr::OriginalName("Cash")] Cash = 1,
    [pbr::OriginalName("CreditCard")] CreditCard = 2,
    [pbr::OriginalName("Voucher")] Voucher = 3,
  }

  #endregion

  #region Messages
  /// <summary>
  /// Messages
  /// </summary>
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class CouponItem : pb::IMessage<CouponItem>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<CouponItem> _parser = new pb::MessageParser<CouponItem>(() => new CouponItem());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<CouponItem> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::SEFApp.Proto.ModelsReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public CouponItem() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public CouponItem(CouponItem other) : this() {
      name_ = other.name_;
      price_ = other.price_;
      unit_ = other.unit_;
      quantity_ = other.quantity_;
      total_ = other.total_;
      taxRate_ = other.taxRate_;
      type_ = other.type_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public CouponItem Clone() {
      return new CouponItem(this);
    }

    /// <summary>Field number for the "name" field.</summary>
    public const int NameFieldNumber = 1;
    private string name_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Name {
      get { return name_; }
      set {
        name_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "price" field.</summary>
    public const int PriceFieldNumber = 2;
    private long price_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long Price {
      get { return price_; }
      set {
        price_ = value;
      }
    }

    /// <summary>Field number for the "unit" field.</summary>
    public const int UnitFieldNumber = 3;
    private string unit_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Unit {
      get { return unit_; }
      set {
        unit_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "quantity" field.</summary>
    public const int QuantityFieldNumber = 4;
    private float quantity_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public float Quantity {
      get { return quantity_; }
      set {
        quantity_ = value;
      }
    }

    /// <summary>Field number for the "total" field.</summary>
    public const int TotalFieldNumber = 5;
    private long total_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long Total {
      get { return total_; }
      set {
        total_ = value;
      }
    }

    /// <summary>Field number for the "tax_rate" field.</summary>
    public const int TaxRateFieldNumber = 6;
    private string taxRate_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string TaxRate {
      get { return taxRate_; }
      set {
        taxRate_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "type" field.</summary>
    public const int TypeFieldNumber = 7;
    private string type_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Type {
      get { return type_; }
      set {
        type_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as CouponItem);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(CouponItem other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Name != other.Name) return false;
      if (Price != other.Price) return false;
      if (Unit != other.Unit) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.Equals(Quantity, other.Quantity)) return false;
      if (Total != other.Total) return false;
      if (TaxRate != other.TaxRate) return false;
      if (Type != other.Type) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Name.Length != 0) hash ^= Name.GetHashCode();
      if (Price != 0L) hash ^= Price.GetHashCode();
      if (Unit.Length != 0) hash ^= Unit.GetHashCode();
      if (Quantity != 0F) hash ^= pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.GetHashCode(Quantity);
      if (Total != 0L) hash ^= Total.GetHashCode();
      if (TaxRate.Length != 0) hash ^= TaxRate.GetHashCode();
      if (Type.Length != 0) hash ^= Type.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Name.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Name);
      }
      if (Price != 0L) {
        output.WriteRawTag(16);
        output.WriteInt64(Price);
      }
      if (Unit.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(Unit);
      }
      if (Quantity != 0F) {
        output.WriteRawTag(37);
        output.WriteFloat(Quantity);
      }
      if (Total != 0L) {
        output.WriteRawTag(40);
        output.WriteInt64(Total);
      }
      if (TaxRate.Length != 0) {
        output.WriteRawTag(50);
        output.WriteString(TaxRate);
      }
      if (Type.Length != 0) {
        output.WriteRawTag(58);
        output.WriteString(Type);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Name.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Name);
      }
      if (Price != 0L) {
        output.WriteRawTag(16);
        output.WriteInt64(Price);
      }
      if (Unit.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(Unit);
      }
      if (Quantity != 0F) {
        output.WriteRawTag(37);
        output.WriteFloat(Quantity);
      }
      if (Total != 0L) {
        output.WriteRawTag(40);
        output.WriteInt64(Total);
      }
      if (TaxRate.Length != 0) {
        output.WriteRawTag(50);
        output.WriteString(TaxRate);
      }
      if (Type.Length != 0) {
        output.WriteRawTag(58);
        output.WriteString(Type);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Name.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Name);
      }
      if (Price != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(Price);
      }
      if (Unit.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Unit);
      }
      if (Quantity != 0F) {
        size += 1 + 4;
      }
      if (Total != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(Total);
      }
      if (TaxRate.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(TaxRate);
      }
      if (Type.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Type);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(CouponItem other) {
      if (other == null) {
        return;
      }
      if (other.Name.Length != 0) {
        Name = other.Name;
      }
      if (other.Price != 0L) {
        Price = other.Price;
      }
      if (other.Unit.Length != 0) {
        Unit = other.Unit;
      }
      if (other.Quantity != 0F) {
        Quantity = other.Quantity;
      }
      if (other.Total != 0L) {
        Total = other.Total;
      }
      if (other.TaxRate.Length != 0) {
        TaxRate = other.TaxRate;
      }
      if (other.Type.Length != 0) {
        Type = other.Type;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            Name = input.ReadString();
            break;
          }
          case 16: {
            Price = input.ReadInt64();
            break;
          }
          case 26: {
            Unit = input.ReadString();
            break;
          }
          case 37: {
            Quantity = input.ReadFloat();
            break;
          }
          case 40: {
            Total = input.ReadInt64();
            break;
          }
          case 50: {
            TaxRate = input.ReadString();
            break;
          }
          case 58: {
            Type = input.ReadString();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            Name = input.ReadString();
            break;
          }
          case 16: {
            Price = input.ReadInt64();
            break;
          }
          case 26: {
            Unit = input.ReadString();
            break;
          }
          case 37: {
            Quantity = input.ReadFloat();
            break;
          }
          case 40: {
            Total = input.ReadInt64();
            break;
          }
          case 50: {
            TaxRate = input.ReadString();
            break;
          }
          case 58: {
            Type = input.ReadString();
            break;
          }
        }
      }
    }
    #endif

  }

  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class Payment : pb::IMessage<Payment>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<Payment> _parser = new pb::MessageParser<Payment>(() => new Payment());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<Payment> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::SEFApp.Proto.ModelsReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Payment() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Payment(Payment other) : this() {
      type_ = other.type_;
      amount_ = other.amount_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Payment Clone() {
      return new Payment(this);
    }

    /// <summary>Field number for the "type" field.</summary>
    public const int TypeFieldNumber = 1;
    private global::SEFApp.Proto.PaymentType type_ = global::SEFApp.Proto.PaymentType.Unspecified;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::SEFApp.Proto.PaymentType Type {
      get { return type_; }
      set {
        type_ = value;
      }
    }

    /// <summary>Field number for the "amount" field.</summary>
    public const int AmountFieldNumber = 2;
    private long amount_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long Amount {
      get { return amount_; }
      set {
        amount_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as Payment);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(Payment other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Type != other.Type) return false;
      if (Amount != other.Amount) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Type != global::SEFApp.Proto.PaymentType.Unspecified) hash ^= Type.GetHashCode();
      if (Amount != 0L) hash ^= Amount.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Type != global::SEFApp.Proto.PaymentType.Unspecified) {
        output.WriteRawTag(8);
        output.WriteEnum((int) Type);
      }
      if (Amount != 0L) {
        output.WriteRawTag(16);
        output.WriteInt64(Amount);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Type != global::SEFApp.Proto.PaymentType.Unspecified) {
        output.WriteRawTag(8);
        output.WriteEnum((int) Type);
      }
      if (Amount != 0L) {
        output.WriteRawTag(16);
        output.WriteInt64(Amount);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Type != global::SEFApp.Proto.PaymentType.Unspecified) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Type);
      }
      if (Amount != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(Amount);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(Payment other) {
      if (other == null) {
        return;
      }
      if (other.Type != global::SEFApp.Proto.PaymentType.Unspecified) {
        Type = other.Type;
      }
      if (other.Amount != 0L) {
        Amount = other.Amount;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Type = (global::SEFApp.Proto.PaymentType) input.ReadEnum();
            break;
          }
          case 16: {
            Amount = input.ReadInt64();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            Type = (global::SEFApp.Proto.PaymentType) input.ReadEnum();
            break;
          }
          case 16: {
            Amount = input.ReadInt64();
            break;
          }
        }
      }
    }
    #endif

  }

  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class TaxGroup : pb::IMessage<TaxGroup>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<TaxGroup> _parser = new pb::MessageParser<TaxGroup>(() => new TaxGroup());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<TaxGroup> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::SEFApp.Proto.ModelsReflection.Descriptor.MessageTypes[2]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public TaxGroup() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public TaxGroup(TaxGroup other) : this() {
      taxRate_ = other.taxRate_;
      totalForTax_ = other.totalForTax_;
      totalTax_ = other.totalTax_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public TaxGroup Clone() {
      return new TaxGroup(this);
    }

    /// <summary>Field number for the "tax_rate" field.</summary>
    public const int TaxRateFieldNumber = 1;
    private string taxRate_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string TaxRate {
      get { return taxRate_; }
      set {
        taxRate_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "total_for_tax" field.</summary>
    public const int TotalForTaxFieldNumber = 2;
    private long totalForTax_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long TotalForTax {
      get { return totalForTax_; }
      set {
        totalForTax_ = value;
      }
    }

    /// <summary>Field number for the "total_tax" field.</summary>
    public const int TotalTaxFieldNumber = 3;
    private long totalTax_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long TotalTax {
      get { return totalTax_; }
      set {
        totalTax_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as TaxGroup);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(TaxGroup other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (TaxRate != other.TaxRate) return false;
      if (TotalForTax != other.TotalForTax) return false;
      if (TotalTax != other.TotalTax) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (TaxRate.Length != 0) hash ^= TaxRate.GetHashCode();
      if (TotalForTax != 0L) hash ^= TotalForTax.GetHashCode();
      if (TotalTax != 0L) hash ^= TotalTax.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (TaxRate.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(TaxRate);
      }
      if (TotalForTax != 0L) {
        output.WriteRawTag(16);
        output.WriteInt64(TotalForTax);
      }
      if (TotalTax != 0L) {
        output.WriteRawTag(24);
        output.WriteInt64(TotalTax);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (TaxRate.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(TaxRate);
      }
      if (TotalForTax != 0L) {
        output.WriteRawTag(16);
        output.WriteInt64(TotalForTax);
      }
      if (TotalTax != 0L) {
        output.WriteRawTag(24);
        output.WriteInt64(TotalTax);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (TaxRate.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(TaxRate);
      }
      if (TotalForTax != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(TotalForTax);
      }
      if (TotalTax != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(TotalTax);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(TaxGroup other) {
      if (other == null) {
        return;
      }
      if (other.TaxRate.Length != 0) {
        TaxRate = other.TaxRate;
      }
      if (other.TotalForTax != 0L) {
        TotalForTax = other.TotalForTax;
      }
      if (other.TotalTax != 0L) {
        TotalTax = other.TotalTax;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            TaxRate = input.ReadString();
            break;
          }
          case 16: {
            TotalForTax = input.ReadInt64();
            break;
          }
          case 24: {
            TotalTax = input.ReadInt64();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            TaxRate = input.ReadString();
            break;
          }
          case 16: {
            TotalForTax = input.ReadInt64();
            break;
          }
          case 24: {
            TotalTax = input.ReadInt64();
            break;
          }
        }
      }
    }
    #endif

  }

  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class PosCoupon : pb::IMessage<PosCoupon>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<PosCoupon> _parser = new pb::MessageParser<PosCoupon>(() => new PosCoupon());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<PosCoupon> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::SEFApp.Proto.ModelsReflection.Descriptor.MessageTypes[3]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public PosCoupon() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public PosCoupon(PosCoupon other) : this() {
      businessId_ = other.businessId_;
      couponId_ = other.couponId_;
      branchId_ = other.branchId_;
      location_ = other.location_;
      operatorId_ = other.operatorId_;
      posId_ = other.posId_;
      applicationId_ = other.applicationId_;
      verificationNo_ = other.verificationNo_;
      type_ = other.type_;
      time_ = other.time_;
      items_ = other.items_.Clone();
      payments_ = other.payments_.Clone();
      total_ = other.total_;
      taxGroups_ = other.taxGroups_.Clone();
      totalTax_ = other.totalTax_;
      totalNoTax_ = other.totalNoTax_;
      referenceNo_ = other.referenceNo_;
      totalDiscount_ = other.totalDiscount_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public PosCoupon Clone() {
      return new PosCoupon(this);
    }

    /// <summary>Field number for the "business_id" field.</summary>
    public const int BusinessIdFieldNumber = 1;
    private ulong businessId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ulong BusinessId {
      get { return businessId_; }
      set {
        businessId_ = value;
      }
    }

    /// <summary>Field number for the "coupon_id" field.</summary>
    public const int CouponIdFieldNumber = 2;
    private ulong couponId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ulong CouponId {
      get { return couponId_; }
      set {
        couponId_ = value;
      }
    }

    /// <summary>Field number for the "branch_id" field.</summary>
    public const int BranchIdFieldNumber = 3;
    private ulong branchId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ulong BranchId {
      get { return branchId_; }
      set {
        branchId_ = value;
      }
    }

    /// <summary>Field number for the "location" field.</summary>
    public const int LocationFieldNumber = 4;
    private string location_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Location {
      get { return location_; }
      set {
        location_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "operator_id" field.</summary>
    public const int OperatorIdFieldNumber = 5;
    private string operatorId_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string OperatorId {
      get { return operatorId_; }
      set {
        operatorId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "pos_id" field.</summary>
    public const int PosIdFieldNumber = 6;
    private ulong posId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ulong PosId {
      get { return posId_; }
      set {
        posId_ = value;
      }
    }

    /// <summary>Field number for the "application_id" field.</summary>
    public const int ApplicationIdFieldNumber = 7;
    private ulong applicationId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ulong ApplicationId {
      get { return applicationId_; }
      set {
        applicationId_ = value;
      }
    }

    /// <summary>Field number for the "verification_no" field.</summary>
    public const int VerificationNoFieldNumber = 8;
    private string verificationNo_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string VerificationNo {
      get { return verificationNo_; }
      set {
        verificationNo_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "type" field.</summary>
    public const int TypeFieldNumber = 9;
    private global::SEFApp.Proto.CouponType type_ = global::SEFApp.Proto.CouponType.Unspecified;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::SEFApp.Proto.CouponType Type {
      get { return type_; }
      set {
        type_ = value;
      }
    }

    /// <summary>Field number for the "time" field.</summary>
    public const int TimeFieldNumber = 10;
    private long time_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long Time {
      get { return time_; }
      set {
        time_ = value;
      }
    }

    /// <summary>Field number for the "items" field.</summary>
    public const int ItemsFieldNumber = 11;
    private static readonly pb::FieldCodec<global::SEFApp.Proto.CouponItem> _repeated_items_codec
        = pb::FieldCodec.ForMessage(90, global::SEFApp.Proto.CouponItem.Parser);
    private readonly pbc::RepeatedField<global::SEFApp.Proto.CouponItem> items_ = new pbc::RepeatedField<global::SEFApp.Proto.CouponItem>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::SEFApp.Proto.CouponItem> Items {
      get { return items_; }
    }

    /// <summary>Field number for the "payments" field.</summary>
    public const int PaymentsFieldNumber = 12;
    private static readonly pb::FieldCodec<global::SEFApp.Proto.Payment> _repeated_payments_codec
        = pb::FieldCodec.ForMessage(98, global::SEFApp.Proto.Payment.Parser);
    private readonly pbc::RepeatedField<global::SEFApp.Proto.Payment> payments_ = new pbc::RepeatedField<global::SEFApp.Proto.Payment>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::SEFApp.Proto.Payment> Payments {
      get { return payments_; }
    }

    /// <summary>Field number for the "total" field.</summary>
    public const int TotalFieldNumber = 13;
    private long total_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long Total {
      get { return total_; }
      set {
        total_ = value;
      }
    }

    /// <summary>Field number for the "tax_groups" field.</summary>
    public const int TaxGroupsFieldNumber = 14;
    private static readonly pb::FieldCodec<global::SEFApp.Proto.TaxGroup> _repeated_taxGroups_codec
        = pb::FieldCodec.ForMessage(114, global::SEFApp.Proto.TaxGroup.Parser);
    private readonly pbc::RepeatedField<global::SEFApp.Proto.TaxGroup> taxGroups_ = new pbc::RepeatedField<global::SEFApp.Proto.TaxGroup>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::SEFApp.Proto.TaxGroup> TaxGroups {
      get { return taxGroups_; }
    }

    /// <summary>Field number for the "total_tax" field.</summary>
    public const int TotalTaxFieldNumber = 15;
    private long totalTax_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long TotalTax {
      get { return totalTax_; }
      set {
        totalTax_ = value;
      }
    }

    /// <summary>Field number for the "total_no_tax" field.</summary>
    public const int TotalNoTaxFieldNumber = 16;
    private long totalNoTax_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long TotalNoTax {
      get { return totalNoTax_; }
      set {
        totalNoTax_ = value;
      }
    }

    /// <summary>Field number for the "reference_no" field.</summary>
    public const int ReferenceNoFieldNumber = 17;
    private ulong referenceNo_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ulong ReferenceNo {
      get { return referenceNo_; }
      set {
        referenceNo_ = value;
      }
    }

    /// <summary>Field number for the "total_discount" field.</summary>
    public const int TotalDiscountFieldNumber = 18;
    private long totalDiscount_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long TotalDiscount {
      get { return totalDiscount_; }
      set {
        totalDiscount_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as PosCoupon);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(PosCoupon other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (BusinessId != other.BusinessId) return false;
      if (CouponId != other.CouponId) return false;
      if (BranchId != other.BranchId) return false;
      if (Location != other.Location) return false;
      if (OperatorId != other.OperatorId) return false;
      if (PosId != other.PosId) return false;
      if (ApplicationId != other.ApplicationId) return false;
      if (VerificationNo != other.VerificationNo) return false;
      if (Type != other.Type) return false;
      if (Time != other.Time) return false;
      if(!items_.Equals(other.items_)) return false;
      if(!payments_.Equals(other.payments_)) return false;
      if (Total != other.Total) return false;
      if(!taxGroups_.Equals(other.taxGroups_)) return false;
      if (TotalTax != other.TotalTax) return false;
      if (TotalNoTax != other.TotalNoTax) return false;
      if (ReferenceNo != other.ReferenceNo) return false;
      if (TotalDiscount != other.TotalDiscount) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (BusinessId != 0UL) hash ^= BusinessId.GetHashCode();
      if (CouponId != 0UL) hash ^= CouponId.GetHashCode();
      if (BranchId != 0UL) hash ^= BranchId.GetHashCode();
      if (Location.Length != 0) hash ^= Location.GetHashCode();
      if (OperatorId.Length != 0) hash ^= OperatorId.GetHashCode();
      if (PosId != 0UL) hash ^= PosId.GetHashCode();
      if (ApplicationId != 0UL) hash ^= ApplicationId.GetHashCode();
      if (VerificationNo.Length != 0) hash ^= VerificationNo.GetHashCode();
      if (Type != global::SEFApp.Proto.CouponType.Unspecified) hash ^= Type.GetHashCode();
      if (Time != 0L) hash ^= Time.GetHashCode();
      hash ^= items_.GetHashCode();
      hash ^= payments_.GetHashCode();
      if (Total != 0L) hash ^= Total.GetHashCode();
      hash ^= taxGroups_.GetHashCode();
      if (TotalTax != 0L) hash ^= TotalTax.GetHashCode();
      if (TotalNoTax != 0L) hash ^= TotalNoTax.GetHashCode();
      if (ReferenceNo != 0UL) hash ^= ReferenceNo.GetHashCode();
      if (TotalDiscount != 0L) hash ^= TotalDiscount.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (BusinessId != 0UL) {
        output.WriteRawTag(8);
        output.WriteUInt64(BusinessId);
      }
      if (CouponId != 0UL) {
        output.WriteRawTag(16);
        output.WriteUInt64(CouponId);
      }
      if (BranchId != 0UL) {
        output.WriteRawTag(24);
        output.WriteUInt64(BranchId);
      }
      if (Location.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(Location);
      }
      if (OperatorId.Length != 0) {
        output.WriteRawTag(42);
        output.WriteString(OperatorId);
      }
      if (PosId != 0UL) {
        output.WriteRawTag(48);
        output.WriteUInt64(PosId);
      }
      if (ApplicationId != 0UL) {
        output.WriteRawTag(56);
        output.WriteUInt64(ApplicationId);
      }
      if (VerificationNo.Length != 0) {
        output.WriteRawTag(66);
        output.WriteString(VerificationNo);
      }
      if (Type != global::SEFApp.Proto.CouponType.Unspecified) {
        output.WriteRawTag(72);
        output.WriteEnum((int) Type);
      }
      if (Time != 0L) {
        output.WriteRawTag(80);
        output.WriteInt64(Time);
      }
      items_.WriteTo(output, _repeated_items_codec);
      payments_.WriteTo(output, _repeated_payments_codec);
      if (Total != 0L) {
        output.WriteRawTag(104);
        output.WriteInt64(Total);
      }
      taxGroups_.WriteTo(output, _repeated_taxGroups_codec);
      if (TotalTax != 0L) {
        output.WriteRawTag(120);
        output.WriteInt64(TotalTax);
      }
      if (TotalNoTax != 0L) {
        output.WriteRawTag(128, 1);
        output.WriteInt64(TotalNoTax);
      }
      if (ReferenceNo != 0UL) {
        output.WriteRawTag(136, 1);
        output.WriteUInt64(ReferenceNo);
      }
      if (TotalDiscount != 0L) {
        output.WriteRawTag(144, 1);
        output.WriteInt64(TotalDiscount);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (BusinessId != 0UL) {
        output.WriteRawTag(8);
        output.WriteUInt64(BusinessId);
      }
      if (CouponId != 0UL) {
        output.WriteRawTag(16);
        output.WriteUInt64(CouponId);
      }
      if (BranchId != 0UL) {
        output.WriteRawTag(24);
        output.WriteUInt64(BranchId);
      }
      if (Location.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(Location);
      }
      if (OperatorId.Length != 0) {
        output.WriteRawTag(42);
        output.WriteString(OperatorId);
      }
      if (PosId != 0UL) {
        output.WriteRawTag(48);
        output.WriteUInt64(PosId);
      }
      if (ApplicationId != 0UL) {
        output.WriteRawTag(56);
        output.WriteUInt64(ApplicationId);
      }
      if (VerificationNo.Length != 0) {
        output.WriteRawTag(66);
        output.WriteString(VerificationNo);
      }
      if (Type != global::SEFApp.Proto.CouponType.Unspecified) {
        output.WriteRawTag(72);
        output.WriteEnum((int) Type);
      }
      if (Time != 0L) {
        output.WriteRawTag(80);
        output.WriteInt64(Time);
      }
      items_.WriteTo(ref output, _repeated_items_codec);
      payments_.WriteTo(ref output, _repeated_payments_codec);
      if (Total != 0L) {
        output.WriteRawTag(104);
        output.WriteInt64(Total);
      }
      taxGroups_.WriteTo(ref output, _repeated_taxGroups_codec);
      if (TotalTax != 0L) {
        output.WriteRawTag(120);
        output.WriteInt64(TotalTax);
      }
      if (TotalNoTax != 0L) {
        output.WriteRawTag(128, 1);
        output.WriteInt64(TotalNoTax);
      }
      if (ReferenceNo != 0UL) {
        output.WriteRawTag(136, 1);
        output.WriteUInt64(ReferenceNo);
      }
      if (TotalDiscount != 0L) {
        output.WriteRawTag(144, 1);
        output.WriteInt64(TotalDiscount);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (BusinessId != 0UL) {
        size += 1 + pb::CodedOutputStream.ComputeUInt64Size(BusinessId);
      }
      if (CouponId != 0UL) {
        size += 1 + pb::CodedOutputStream.ComputeUInt64Size(CouponId);
      }
      if (BranchId != 0UL) {
        size += 1 + pb::CodedOutputStream.ComputeUInt64Size(BranchId);
      }
      if (Location.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Location);
      }
      if (OperatorId.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(OperatorId);
      }
      if (PosId != 0UL) {
        size += 1 + pb::CodedOutputStream.ComputeUInt64Size(PosId);
      }
      if (ApplicationId != 0UL) {
        size += 1 + pb::CodedOutputStream.ComputeUInt64Size(ApplicationId);
      }
      if (VerificationNo.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(VerificationNo);
      }
      if (Type != global::SEFApp.Proto.CouponType.Unspecified) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Type);
      }
      if (Time != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(Time);
      }
      size += items_.CalculateSize(_repeated_items_codec);
      size += payments_.CalculateSize(_repeated_payments_codec);
      if (Total != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(Total);
      }
      size += taxGroups_.CalculateSize(_repeated_taxGroups_codec);
      if (TotalTax != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(TotalTax);
      }
      if (TotalNoTax != 0L) {
        size += 2 + pb::CodedOutputStream.ComputeInt64Size(TotalNoTax);
      }
      if (ReferenceNo != 0UL) {
        size += 2 + pb::CodedOutputStream.ComputeUInt64Size(ReferenceNo);
      }
      if (TotalDiscount != 0L) {
        size += 2 + pb::CodedOutputStream.ComputeInt64Size(TotalDiscount);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(PosCoupon other) {
      if (other == null) {
        return;
      }
      if (other.BusinessId != 0UL) {
        BusinessId = other.BusinessId;
      }
      if (other.CouponId != 0UL) {
        CouponId = other.CouponId;
      }
      if (other.BranchId != 0UL) {
        BranchId = other.BranchId;
      }
      if (other.Location.Length != 0) {
        Location = other.Location;
      }
      if (other.OperatorId.Length != 0) {
        OperatorId = other.OperatorId;
      }
      if (other.PosId != 0UL) {
        PosId = other.PosId;
      }
      if (other.ApplicationId != 0UL) {
        ApplicationId = other.ApplicationId;
      }
      if (other.VerificationNo.Length != 0) {
        VerificationNo = other.VerificationNo;
      }
      if (other.Type != global::SEFApp.Proto.CouponType.Unspecified) {
        Type = other.Type;
      }
      if (other.Time != 0L) {
        Time = other.Time;
      }
      items_.Add(other.items_);
      payments_.Add(other.payments_);
      if (other.Total != 0L) {
        Total = other.Total;
      }
      taxGroups_.Add(other.taxGroups_);
      if (other.TotalTax != 0L) {
        TotalTax = other.TotalTax;
      }
      if (other.TotalNoTax != 0L) {
        TotalNoTax = other.TotalNoTax;
      }
      if (other.ReferenceNo != 0UL) {
        ReferenceNo = other.ReferenceNo;
      }
      if (other.TotalDiscount != 0L) {
        TotalDiscount = other.TotalDiscount;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            BusinessId = input.ReadUInt64();
            break;
          }
          case 16: {
            CouponId = input.ReadUInt64();
            break;
          }
          case 24: {
            BranchId = input.ReadUInt64();
            break;
          }
          case 34: {
            Location = input.ReadString();
            break;
          }
          case 42: {
            OperatorId = input.ReadString();
            break;
          }
          case 48: {
            PosId = input.ReadUInt64();
            break;
          }
          case 56: {
            ApplicationId = input.ReadUInt64();
            break;
          }
          case 66: {
            VerificationNo = input.ReadString();
            break;
          }
          case 72: {
            Type = (global::SEFApp.Proto.CouponType) input.ReadEnum();
            break;
          }
          case 80: {
            Time = input.ReadInt64();
            break;
          }
          case 90: {
            items_.AddEntriesFrom(input, _repeated_items_codec);
            break;
          }
          case 98: {
            payments_.AddEntriesFrom(input, _repeated_payments_codec);
            break;
          }
          case 104: {
            Total = input.ReadInt64();
            break;
          }
          case 114: {
            taxGroups_.AddEntriesFrom(input, _repeated_taxGroups_codec);
            break;
          }
          case 120: {
            TotalTax = input.ReadInt64();
            break;
          }
          case 128: {
            TotalNoTax = input.ReadInt64();
            break;
          }
          case 136: {
            ReferenceNo = input.ReadUInt64();
            break;
          }
          case 144: {
            TotalDiscount = input.ReadInt64();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            BusinessId = input.ReadUInt64();
            break;
          }
          case 16: {
            CouponId = input.ReadUInt64();
            break;
          }
          case 24: {
            BranchId = input.ReadUInt64();
            break;
          }
          case 34: {
            Location = input.ReadString();
            break;
          }
          case 42: {
            OperatorId = input.ReadString();
            break;
          }
          case 48: {
            PosId = input.ReadUInt64();
            break;
          }
          case 56: {
            ApplicationId = input.ReadUInt64();
            break;
          }
          case 66: {
            VerificationNo = input.ReadString();
            break;
          }
          case 72: {
            Type = (global::SEFApp.Proto.CouponType) input.ReadEnum();
            break;
          }
          case 80: {
            Time = input.ReadInt64();
            break;
          }
          case 90: {
            items_.AddEntriesFrom(ref input, _repeated_items_codec);
            break;
          }
          case 98: {
            payments_.AddEntriesFrom(ref input, _repeated_payments_codec);
            break;
          }
          case 104: {
            Total = input.ReadInt64();
            break;
          }
          case 114: {
            taxGroups_.AddEntriesFrom(ref input, _repeated_taxGroups_codec);
            break;
          }
          case 120: {
            TotalTax = input.ReadInt64();
            break;
          }
          case 128: {
            TotalNoTax = input.ReadInt64();
            break;
          }
          case 136: {
            ReferenceNo = input.ReadUInt64();
            break;
          }
          case 144: {
            TotalDiscount = input.ReadInt64();
            break;
          }
        }
      }
    }
    #endif

  }

  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class CitizenCoupon : pb::IMessage<CitizenCoupon>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<CitizenCoupon> _parser = new pb::MessageParser<CitizenCoupon>(() => new CitizenCoupon());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<CitizenCoupon> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::SEFApp.Proto.ModelsReflection.Descriptor.MessageTypes[4]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public CitizenCoupon() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public CitizenCoupon(CitizenCoupon other) : this() {
      businessId_ = other.businessId_;
      posId_ = other.posId_;
      couponId_ = other.couponId_;
      branchId_ = other.branchId_;
      type_ = other.type_;
      time_ = other.time_;
      total_ = other.total_;
      taxGroups_ = other.taxGroups_.Clone();
      totalTax_ = other.totalTax_;
      totalNoTax_ = other.totalNoTax_;
      totalDiscount_ = other.totalDiscount_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public CitizenCoupon Clone() {
      return new CitizenCoupon(this);
    }

    /// <summary>Field number for the "business_id" field.</summary>
    public const int BusinessIdFieldNumber = 1;
    private ulong businessId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ulong BusinessId {
      get { return businessId_; }
      set {
        businessId_ = value;
      }
    }

    /// <summary>Field number for the "pos_id" field.</summary>
    public const int PosIdFieldNumber = 2;
    private ulong posId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ulong PosId {
      get { return posId_; }
      set {
        posId_ = value;
      }
    }

    /// <summary>Field number for the "coupon_id" field.</summary>
    public const int CouponIdFieldNumber = 3;
    private ulong couponId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ulong CouponId {
      get { return couponId_; }
      set {
        couponId_ = value;
      }
    }

    /// <summary>Field number for the "branch_id" field.</summary>
    public const int BranchIdFieldNumber = 4;
    private ulong branchId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ulong BranchId {
      get { return branchId_; }
      set {
        branchId_ = value;
      }
    }

    /// <summary>Field number for the "type" field.</summary>
    public const int TypeFieldNumber = 5;
    private global::SEFApp.Proto.CouponType type_ = global::SEFApp.Proto.CouponType.Unspecified;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::SEFApp.Proto.CouponType Type {
      get { return type_; }
      set {
        type_ = value;
      }
    }

    /// <summary>Field number for the "time" field.</summary>
    public const int TimeFieldNumber = 6;
    private long time_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long Time {
      get { return time_; }
      set {
        time_ = value;
      }
    }

    /// <summary>Field number for the "total" field.</summary>
    public const int TotalFieldNumber = 7;
    private long total_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long Total {
      get { return total_; }
      set {
        total_ = value;
      }
    }

    /// <summary>Field number for the "tax_groups" field.</summary>
    public const int TaxGroupsFieldNumber = 8;
    private static readonly pb::FieldCodec<global::SEFApp.Proto.TaxGroup> _repeated_taxGroups_codec
        = pb::FieldCodec.ForMessage(66, global::SEFApp.Proto.TaxGroup.Parser);
    private readonly pbc::RepeatedField<global::SEFApp.Proto.TaxGroup> taxGroups_ = new pbc::RepeatedField<global::SEFApp.Proto.TaxGroup>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::SEFApp.Proto.TaxGroup> TaxGroups {
      get { return taxGroups_; }
    }

    /// <summary>Field number for the "total_tax" field.</summary>
    public const int TotalTaxFieldNumber = 9;
    private long totalTax_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long TotalTax {
      get { return totalTax_; }
      set {
        totalTax_ = value;
      }
    }

    /// <summary>Field number for the "total_no_tax" field.</summary>
    public const int TotalNoTaxFieldNumber = 10;
    private long totalNoTax_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long TotalNoTax {
      get { return totalNoTax_; }
      set {
        totalNoTax_ = value;
      }
    }

    /// <summary>Field number for the "total_discount" field.</summary>
    public const int TotalDiscountFieldNumber = 11;
    private long totalDiscount_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long TotalDiscount {
      get { return totalDiscount_; }
      set {
        totalDiscount_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as CitizenCoupon);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(CitizenCoupon other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (BusinessId != other.BusinessId) return false;
      if (PosId != other.PosId) return false;
      if (CouponId != other.CouponId) return false;
      if (BranchId != other.BranchId) return false;
      if (Type != other.Type) return false;
      if (Time != other.Time) return false;
      if (Total != other.Total) return false;
      if(!taxGroups_.Equals(other.taxGroups_)) return false;
      if (TotalTax != other.TotalTax) return false;
      if (TotalNoTax != other.TotalNoTax) return false;
      if (TotalDiscount != other.TotalDiscount) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (BusinessId != 0UL) hash ^= BusinessId.GetHashCode();
      if (PosId != 0UL) hash ^= PosId.GetHashCode();
      if (CouponId != 0UL) hash ^= CouponId.GetHashCode();
      if (BranchId != 0UL) hash ^= BranchId.GetHashCode();
      if (Type != global::SEFApp.Proto.CouponType.Unspecified) hash ^= Type.GetHashCode();
      if (Time != 0L) hash ^= Time.GetHashCode();
      if (Total != 0L) hash ^= Total.GetHashCode();
      hash ^= taxGroups_.GetHashCode();
      if (TotalTax != 0L) hash ^= TotalTax.GetHashCode();
      if (TotalNoTax != 0L) hash ^= TotalNoTax.GetHashCode();
      if (TotalDiscount != 0L) hash ^= TotalDiscount.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (BusinessId != 0UL) {
        output.WriteRawTag(8);
        output.WriteUInt64(BusinessId);
      }
      if (PosId != 0UL) {
        output.WriteRawTag(16);
        output.WriteUInt64(PosId);
      }
      if (CouponId != 0UL) {
        output.WriteRawTag(24);
        output.WriteUInt64(CouponId);
      }
      if (BranchId != 0UL) {
        output.WriteRawTag(32);
        output.WriteUInt64(BranchId);
      }
      if (Type != global::SEFApp.Proto.CouponType.Unspecified) {
        output.WriteRawTag(40);
        output.WriteEnum((int) Type);
      }
      if (Time != 0L) {
        output.WriteRawTag(48);
        output.WriteInt64(Time);
      }
      if (Total != 0L) {
        output.WriteRawTag(56);
        output.WriteInt64(Total);
      }
      taxGroups_.WriteTo(output, _repeated_taxGroups_codec);
      if (TotalTax != 0L) {
        output.WriteRawTag(72);
        output.WriteInt64(TotalTax);
      }
      if (TotalNoTax != 0L) {
        output.WriteRawTag(80);
        output.WriteInt64(TotalNoTax);
      }
      if (TotalDiscount != 0L) {
        output.WriteRawTag(88);
        output.WriteInt64(TotalDiscount);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (BusinessId != 0UL) {
        output.WriteRawTag(8);
        output.WriteUInt64(BusinessId);
      }
      if (PosId != 0UL) {
        output.WriteRawTag(16);
        output.WriteUInt64(PosId);
      }
      if (CouponId != 0UL) {
        output.WriteRawTag(24);
        output.WriteUInt64(CouponId);
      }
      if (BranchId != 0UL) {
        output.WriteRawTag(32);
        output.WriteUInt64(BranchId);
      }
      if (Type != global::SEFApp.Proto.CouponType.Unspecified) {
        output.WriteRawTag(40);
        output.WriteEnum((int) Type);
      }
      if (Time != 0L) {
        output.WriteRawTag(48);
        output.WriteInt64(Time);
      }
      if (Total != 0L) {
        output.WriteRawTag(56);
        output.WriteInt64(Total);
      }
      taxGroups_.WriteTo(ref output, _repeated_taxGroups_codec);
      if (TotalTax != 0L) {
        output.WriteRawTag(72);
        output.WriteInt64(TotalTax);
      }
      if (TotalNoTax != 0L) {
        output.WriteRawTag(80);
        output.WriteInt64(TotalNoTax);
      }
      if (TotalDiscount != 0L) {
        output.WriteRawTag(88);
        output.WriteInt64(TotalDiscount);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (BusinessId != 0UL) {
        size += 1 + pb::CodedOutputStream.ComputeUInt64Size(BusinessId);
      }
      if (PosId != 0UL) {
        size += 1 + pb::CodedOutputStream.ComputeUInt64Size(PosId);
      }
      if (CouponId != 0UL) {
        size += 1 + pb::CodedOutputStream.ComputeUInt64Size(CouponId);
      }
      if (BranchId != 0UL) {
        size += 1 + pb::CodedOutputStream.ComputeUInt64Size(BranchId);
      }
      if (Type != global::SEFApp.Proto.CouponType.Unspecified) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Type);
      }
      if (Time != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(Time);
      }
      if (Total != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(Total);
      }
      size += taxGroups_.CalculateSize(_repeated_taxGroups_codec);
      if (TotalTax != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(TotalTax);
      }
      if (TotalNoTax != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(TotalNoTax);
      }
      if (TotalDiscount != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(TotalDiscount);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(CitizenCoupon other) {
      if (other == null) {
        return;
      }
      if (other.BusinessId != 0UL) {
        BusinessId = other.BusinessId;
      }
      if (other.PosId != 0UL) {
        PosId = other.PosId;
      }
      if (other.CouponId != 0UL) {
        CouponId = other.CouponId;
      }
      if (other.BranchId != 0UL) {
        BranchId = other.BranchId;
      }
      if (other.Type != global::SEFApp.Proto.CouponType.Unspecified) {
        Type = other.Type;
      }
      if (other.Time != 0L) {
        Time = other.Time;
      }
      if (other.Total != 0L) {
        Total = other.Total;
      }
      taxGroups_.Add(other.taxGroups_);
      if (other.TotalTax != 0L) {
        TotalTax = other.TotalTax;
      }
      if (other.TotalNoTax != 0L) {
        TotalNoTax = other.TotalNoTax;
      }
      if (other.TotalDiscount != 0L) {
        TotalDiscount = other.TotalDiscount;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            BusinessId = input.ReadUInt64();
            break;
          }
          case 16: {
            PosId = input.ReadUInt64();
            break;
          }
          case 24: {
            CouponId = input.ReadUInt64();
            break;
          }
          case 32: {
            BranchId = input.ReadUInt64();
            break;
          }
          case 40: {
            Type = (global::SEFApp.Proto.CouponType) input.ReadEnum();
            break;
          }
          case 48: {
            Time = input.ReadInt64();
            break;
          }
          case 56: {
            Total = input.ReadInt64();
            break;
          }
          case 66: {
            taxGroups_.AddEntriesFrom(input, _repeated_taxGroups_codec);
            break;
          }
          case 72: {
            TotalTax = input.ReadInt64();
            break;
          }
          case 80: {
            TotalNoTax = input.ReadInt64();
            break;
          }
          case 88: {
            TotalDiscount = input.ReadInt64();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            BusinessId = input.ReadUInt64();
            break;
          }
          case 16: {
            PosId = input.ReadUInt64();
            break;
          }
          case 24: {
            CouponId = input.ReadUInt64();
            break;
          }
          case 32: {
            BranchId = input.ReadUInt64();
            break;
          }
          case 40: {
            Type = (global::SEFApp.Proto.CouponType) input.ReadEnum();
            break;
          }
          case 48: {
            Time = input.ReadInt64();
            break;
          }
          case 56: {
            Total = input.ReadInt64();
            break;
          }
          case 66: {
            taxGroups_.AddEntriesFrom(ref input, _repeated_taxGroups_codec);
            break;
          }
          case 72: {
            TotalTax = input.ReadInt64();
            break;
          }
          case 80: {
            TotalNoTax = input.ReadInt64();
            break;
          }
          case 88: {
            TotalDiscount = input.ReadInt64();
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
